POST http://localhost:3003/api/blogs
content-type: application/json

{
  "title": "teko",
  "author": "Ropettaja",
  "url": "joku.com",
  "likes": 1
}

###
PUT http://localhost:3003/api/blogs/6458bf2de609e510c0c095b8

{
  "title": "putteri",
  "author": "Puttaaja",
  "url": "eiole",
  "likes": 4
}