POST http://localhost:3003/api/users
content-type: application/json

{
  "username": "Mir0Va",
  "name": "Miro",
  "password": "salasana"
}

###
DELETE  http://localhost:3003/api/blogs/645a131d68a75cca425e88d0
Authorization: Bearer 

###
POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: Bearer

{
  "title": "testing",
  "author": "Mir",
  "url": "no"
}

###
POST http://localhost:3003/api/login
content-type: application/json

{
  "username": "Mir0Va",
  "password": "salasana"
}
